<?php
return [

'SERVICES'=>"SERVICES",	
'SERVICE_ADD' => "SERVICE_ADD",
'SERVICE_ALL' => "SERVICE_ALL",
'SERVICE_DETAILS' => "SERVICE_DETAILS",
'SERVICE_UPDATE' => "SERVICE_UPDATE",

'SUBSERVICE_ADD' => "SUBSERVICE_ADD",
'SUBSERVICE_ALL' => "SUBSERVICE_ALL",
'SUBSERVICE_DETAILS' => "SUBSERVICE_DETAILS",
'SUBSERVICE_UPDATE' => "SUBSERVICE_UPDATE",

'BANKS'=>"BANKS",
'BANK_ADD' => "BANK_ADD",
'BANK_ALL' => "BANK_ALL",
'BANK_DETAILS' => "BANK_DETAILS",
'BANK_UPDATE' => "BANK_UPDATE",

'COMMISSION_ADD' => "COMMISSION_ADD",	
'COMMISSION_ALL' => "COMMISSION_ALL",
'COMMISSION_DETAILS' => "COMMISSION_DETAILS",
'COMMISSION_UPDATE' => "COMMISSION_UPDATE",

'TRAINING_ADD' => "TRAINING_ADD",
'TRAINING_ALL' => "TRAINING_ALL",
'TRAINING_DETAILS' => "TRAINING_DETAILS",
'TRAINING_UPDATE' => "TRAINING_UPDATE",
'TRAINING_VIEW' => "TRAINING_VIEW",

'CUSTOMERS' => "CUSTOMERS",
'CUSTOMER_ADD' => "CUSTOMER_ADD",
'CUSTOMER_ALL' => "CUSTOMER_ALL",
'CUSTOMER_DETAILS' => "CUSTOMER_DETAILS",
'CUSTOMER_UPDATE' => "CUSTOMER_UPDATE",

'AGENT_ADD'=>"AGENT_ADD",
'AGENT_ALL' => "AGENT_ALL",
'AGENT_DETAILS' => "AGENT_DETAILS",
'AGENT_UPDATE' => "AGENT_UPDATE",
'DELIVERY_STATUS_UPDATE' => "DELIVERY_STATUS_UPDATE",

'SUPPORT'=>"SUPPORT",
'SUPPORT_ADD' => "SUPPORT_ADD",
'SUPPORT_ALL' => "SUPPORT_ALL",
'SUPPORT_DETAILS' => "SUPPORT_DETAILS",
'SUPPORT_UPDATE' => "SUPPORT_UPDATE",

'NOTIFICATIONS'=>"NOTIFICATIONS",
'NOTIFICATION_ADD' => "NOTIFICATION_ADD",
'NOTIFICATION_ALL' => "NOTIFICATION_ALL",
'NOTIFICATION_DETAILS' => "NOTIFICATION_DETAILS",
'NOTIFICATION_UPDATE' => "NOTIFICATION_UPDATE",

'DOWNLOAD'=>'DOWNLOAD',

'COMMISSION_REPORT_ACTION'=>'COMMISSION_REPORT_ACTION',

'IMPORT'=>'IMPORT',

'REPORT'=>'REPORT',
'AGENT_REPORT'=>'AGENT_REPORT',
'ALL_CUSTOMER_REPORT'=>'ALL_CUSTOMER_REPORT',
'COMMISSION_REPORT' => "COMMISSION_REPORT",
'LOAN_REPORT' => "LOAN_REPORT",

'CHANGE_PASSWORD'=>"CHANGE_PASSWORD",

'PERMISSION'=>"PERMISSION",
'PERMISSION_ADD' => "PERMISSION_ADD",
'PERMISSION_ALL' => "PERMISSION_ALL",
'PERMISSION_DETAILS' => "PERMISSION_DETAILS",
'PERMISSION_UPDATE' => "PERMISSION_UPDATE",

'PINCODE'=>"PINCODE",
'PINCODE_ADD' => "PINCODE_ADD",
'PINCODE_ALL' => "PINCODE_ALL",
'PINCODE_DETAILS' => "PINCODE_DETAILS",
'PINCODE_UPDATE' => "PINCODE_UPDATE",

'POLICIES'=>"POLICIES",
'POLICY_ADD' => "POLICY_ADD",
'POLICY_ALL' => "POLICY_ALL",
'POLICY_DETAILS' => "POLICY_DETAILS",
'POLICY_UPDATE' => "POLICY_UPDATE",

'PRODUCTS'=>"PRODUCTS",
'PRODUCT_ADD' => "PRODUCT_ADD",
'PRODUCT_ALL' => "PRODUCT_ALL",
'PRODUCT_DETAILS' => "PRODUCT_DETAILS",
'PRODUCT_UPDATE' => "PRODUCT_UPDATE",
'PRODUCT_SELLER'=>"PRODUCT_SELLER",
'PRODUCT_SELLER'=>'PRODUCT_SELLER',


'ROLES'=>"ROLES",
'ROLE_ADD' => "ROLE_ADD",
'ROLE_ALL' => "ROLE_ALL",
'ROLE_DETAILS' => "ROLE_DETAILS",
'ROLE_UPDATE' => "ROLE_UPDATE",

'SETTING' => "SETTING",


'SUBADMINS'=>"SUBADMINS",
'SUBADMIN_ADD' => "SUBADMIN_ADD",
'SUBADMIN_ALL' => "SUBADMIN_ALL",
'SUBADMIN_DETAILS' => "SUBADMIN_DETAILS",
'SUBADMIN_UPDATE' => "SUBADMIN_UPDATE",

'ADMINS'=>"ADMINS",
'ADMIN_ADD' => "ADMIN_ADD",
'ADMIN_ALL' => "ADMIN_ALL",
'ADMIN_DETAILS' => "ADMIN_DETAILS",
'ADMIN_UPDATE' => "ADMIN_UPDATE",

'SUBSELLERS'=>"SUBSELLERS",
'SUBSELLER_ADD' => "SUBSELLER_ADD",
'SUBSELLER_ALL' => "SUBSELLER_ALL",
'SUBSELLER_DETAILS' => "SUBSELLER_DETAILS",
'SUBSELLER_UPDATE' => "SUBSELLER_UPDATE",

'USER_ADD' => "USER_ADD",
'USER_ALL' => "USER_ALL",
'USER_DETAILS' => "USER_DETAILS",
'USER_UPDATE' => "USER_UPDATE",	

'SUPPORT' => "SUPPORT",

'DASHBOARD' => "DASHBOARD",

'REASON_ADD'=>"REASON_ADD",
'REASON_ALL'=>"REASON_ALL",
'REASON_DETAILS'=>"REASON_DETAILS",
'REASON_VIEW'=>"REASON_VIEW",

'SUBAGENT'=>'SUBAGENT',
'SUBAGENT_ALL'=>'SUBAGENT_ALL',
'SUBAGENT_ADD'=>'SUBAGENT_ADD',
'SUBAGENT_DETAILS'=>'SUBAGENT_DETAILS',

'INVENTORY_ALL'=>"INVENTORY_ALL",
'INVENTORY_UPDATE'=>"INVENTORY_UPDATE",

'PROMOCODE'=>"PROMOCODE",
'PROMOCODE_ADD' => "PROMOCODE_ADD",
'PROMOCODE_ALL' => "PROMOCODE_ALL",
'PROMOCODE_DETAILS' => "PROMOCODE_DETAILS",
'PROMOCODE_UPDATE' => "PROMOCODE_UPDATE",

'PROMOCODECONDITIONS'=>"PROMOCODECONDITIONS",
'PROMOCODECONDITION_ADD' => "PROMOCODECONDITION_ADD",
'PROMOCODECONDITION_ALL' => "PROMOCODECONDITION_ALL",
'PROMOCODECONDITION_DETAILS' => "PROMOCODECONDITION_DETAILS",
'PROMOCODECONDITION_UPDATE' => "PROMOCODECONDITION_UPDATE",

'PAYMENTOPTION_VIEW' => "PAYMENTOPTION_VIEW",
'PAYMENTOPTION_UPDATE' => "PAYMENTOPTION_UPDATE",

'DELIVERYOPTION_VIEW' => 'DELIVERYOPTION_VIEW',
'DELIVERYOPTION_UPDATE' => 'DELIVERYOPTION_UPDATE',

'APPLICATIONAPPEARANCE_VIEW' => 'APPLICATIONAPPEARANCE_VIEW',
'APPLICATIONAPPEARANCE_UPDATE' => 'APPLICATIONAPPEARANCE_UPDATE',

'REGISTRATIONFORM_VIEW' => 'REGISTRATIONFORM_VIEW',
'REGISTRATIONFORM_UPDATE' => 'REGISTRATIONFORM_UPDATE',

'APPEARANCETRANSLATION_VIEW'=>'APPEARANCETRANSLATION_VIEW',
'APPEARANCETRANSLATION_UPDATE'=>'APPEARANCETRANSLATION_UPDATE',

'BRANDS'=>'BRANDS',

'AREAS'=>'AREAS',
'AREA_ADD' => 'AREA_ADD',
'AREA_ALL' => 'AREA_ALL',
'AREA_DETAILS' => 'AREA_DETAILS',
'AREA_UPDATE' => 'AREA_UPDATE',

'DELIVERY_BOYS'=>'DELIVERY_BOYS',
'DELIVERY_BOY_ADD' => 'DELIVERY_BOY_ADD',
'DELIVERY_BOY_ALL' => 'DELIVERY_BOY_ALL',
'DELIVERY_BOY_DETAILS' => 'DELIVERY_BOY_DETAILS',
'DELIVERY_BOY_UPDATE' => 'DELIVERY_BOY_UPDATE',

'BRAND_ADD'=>'BRAND_ADD',
'BRAND_ALL'=>'BRAND_ALL',
'BRAND_DETAILS'=>'BRAND_DETAILS',
'BRAND_UPDATE'=>'BRAND_UPDATE',

'AREA_ASSIGNMENTS'=>'AREA_ASSIGNMENTS',
'AREA_ASSIGNMENT_ADD'=>'AREA_ASSIGNMENT_ADD',
'AREA_ASSIGNMENT_ALL'=>'AREA_ASSIGNMENT_ALL',
'AREA_ASSIGNMENT_DETAILS'=>'AREA_ASSIGNMENT_DETAILS',
'AREA_ASSIGNMENT_UPDATE'=>'AREA_ASSIGNMENT_UPDATE',

'PINCODE_ASSIGNMENTS'=>'PINCODE_ASSIGNMENTS',
'PINCODE_ASSIGNMENT_ADD'=>'PINCODE_ASSIGNMENT_ADD',
'PINCODE_ASSIGNMENT_ALL'=>'PINCODE_ASSIGNMENT_ALL',
'PINCODE_ASSIGNMENT_DETAILS'=>'PINCODE_ASSIGNMENT_DETAILS',
'PINCODE_ASSIGNMENT_UPDATE'=>'PINCODE_ASSIGNMENT_UPDATE',

'LANGUAGES'=>'LANGUAGES',
'LANGUAGE_ALL'=>'LANGUAGE_ALL',
'LANGUAGE_DETAILS'=>'LANGUAGE_DETAILS',
'LANGUAGE_UPDATE'=>'LANGUAGE_UPDATE',

'PARENT_VARIANTS'=>'PARENT_VARIANTS',
'PARENT_VARIANT_ADD'=>'PARENT_VARIANT_ADD',
'PARENT_VARIANT_ALL'=>'PARENT_VARIANT_ALL',
'PARENT_VARIANT_DETAILS'=>'PARENT_VARIANT_DETAILS',
'PARENT_VARIANT_UPDATE'=>'PARENT_VARIANT_UPDATE',

'CHILD_VARIANTS'=>'CHILD_VARIANTS',
'CHILD_VARIANT_ADD'=>'CHILD_VARIANT_ADD',
'CHILD_VARIANT_ALL'=>'CHILD_VARIANT_ALL',
'CHILD_VARIANT_DETAILS'=>'CHILD_VARIANT_DETAILS',
'CHILD_VARIANT_UPDATE'=>'CHILD_VARIANT_UPDATE',

'TERM_CONDITIONS' => 'TERM_CONDITIONS',
'TERM_CONDITION_ADD'=>'TERM_CONDITION_ADD',
'TERM_CONDITION_ALL'=>'TERM_CONDITION_ALL',
'TERM_CONDITION_DETAILS'=>'TERM_CONDITION_DETAILS',
'TERM_CONDITION_UPDATE'=>'TERM_CONDITION_UPDATE',

'NAVIGATION_LABELS' => 'NAVIGATION_LABELS',
'NAVIGATION_LABEL_ADD'=>'NAVIGATION_LABEL_ADD',
'NAVIGATION_LABEL_ALL'=>'NAVIGATION_LABEL_ALL',
'NAVIGATION_LABEL_DETAILS'=>'NAVIGATION_LABEL_DETAILS',
'NAVIGATION_LABEL_UPDATE'=>'NAVIGATION_LABEL_UPDATE',

//Wallet label
'WALLET' => 'WALLET',
'WALLET_ALL'=>'WALLET_ALL',
'WALLET_ADD'=>'WALLET_ADD',
'WALLET_DETAILS'=>'WALLET_DETAILS',

//Cart Label
'CART_LABELS' => 'CART_LABELS',
'CART_LABEL_ADD'=>'CART_LABEL_ADD',
'CART_LABEL_ALL'=>'CART_LABEL_ALL',
'CART_LABEL_DETAILS'=>'CART_LABEL_DETAILS',
'CART_LABEL_UPDATE'=>'CART_LABEL_UPDATE',

//Country
'COUNTRY' => 'COUNTRY',
'COUNTRY_ADD'=>'COUNTRY_ADD',
'COUNTRY_ALL'=>'COUNTRY_ALL',
'COUNTRY_DETAILS'=>'COUNTRY_DETAILS',
'COUNTRY_UPDATE'=>'COUNTRY_UPDATE',

//State
'STATE' => 'STATE',
'STATE_ADD'=>'STATE_ADD',
'STATE_ALL'=>'STATE_ALL',
'STATE_DETAILS'=>'STATE_DETAILS',
'STATE_UPDATE'=>'STATE_UPDATE',

//City
'CITY' => 'CITY',
'CITY_ADD'=>'CITY_ADD',
'CITY_ALL'=>'CITY_ALL',
'CITY_DETAILS'=>'CITY_DETAILS',
'CITY_UPDATE'=>'CITY_UPDATE',

//Variant
'VARIANTS'=>'VARIANTS',
'VARIANT_ADD'=>'VARIANT_ADD',
'VARIANT_ALL'=>'VARIANT_ALL',
'VARIANT_DETAILS'=>'VARIANT_DETAILS',
'VARIANT_UPDATE'=>'VARIANT_UPDATE',
'VARIANT_MENU'=>'VARIANT_MENU',

//Offer block
'OFFER_BLOCK' =>"OFFER_BLOCK",
'OFFER_BLOCK_ADD' => "OFFER_BLOCK_ADD",
'OFFER_BLOCK_ALL' => "OFFER_BLOCK_ALL",
'OFFER_BLOCK_DETAILS' => "OFFER_BLOCK_DETAILS",
'OFFER_BLOCK_UPDATE' => "OFFER_BLOCK_UPDATE",

//Addressform
'ADDRESS_FORM_VIEW' => 'ADDRESS_FORM_VIEW',
'ADDRESS_FORM_UPDATE' => 'ADDRESS_FORM_UPDATE',


//profile setting form
'PROFILE_SETTING_VIEW' => 'PROFILE_SETTING_VIEW',
'PROFILE_SETTING_UPDATE' => 'PROFILE_SETTING_UPDATE',

//EMAIL CONFIGURATION
'VIEW_EMAIL_CONFIGURATION' => 'VIEW_EMAIL_CONFIGURATION',
'UPDATE_EMAIL_CONFIGURATION' => 'UPDATE_EMAIL_CONFIGURATION',

//DELIVERY VENDOR
	'DELIVERY_VENDORS' => 'DELIVERY_VENDORS',
	'DELIVERY_VENDOR_ALL' => 'DELIVERY_VENDOR_ALL',
	'DELIVERY_VENDOR_ADD' => 'DELIVERY_VENDOR_ADD',
	'DELIVERY_VENDOR_UPDATE' => 'DELIVERY_VENDOR_UPDATE',

//UserManagement
'USER_MANAGEMENT' => 'USER_MANAGEMENT',

//Manage Location
'MANAGE_LOCATION' => 'MANAGE_LOCATION',

//View Variant in menu
'VIEW_VARINAT' => 'VIEW_VARIANT',

'CREATE_ORDER'=>"CREATE_ORDER",

'CONTACT_US' =>'CONTACT_US',

'CONTACT_US_ALL'=>'CONTACT_US_ALL',

'HOME'=> 'HOME',



'RETURN_POLICY_ALL'=>'RETURN_POLICY_ALL',

'RETURN_POLICY'=>'RETURN_POLICY',

'ABOUTUS_ADD'=>'ABOUTUS_ADD',

'APPLICATION_SETTING'=>'APPLICATION_SETTING',

	// POS
'POS'=>'POS',
'STORE_ALL'=>'STORE_ALL',
'STORE_ADD'=>'STORE_ADD',
'GET_STORE'=>'GET_STORE',
'STORE_INVENTORY'=>'STORE_INVENTORY',
'ALL_VENDOR'=>'ALL_VENDOR',
'ADD_VENDOR'=>'ADD_VENDOR',
'EDIT_STORE'=>'EDIT_STORE',
'UPDATE_STORE'=>'UPDATE_STORE',
'ADD_STORE_USER'=>'ADD_STORE_USER',
'ALL_STORE_USER'=>'ALL_STORE_USER',
'ALL_PURCHASE_ORDER'=>'ALL_PURCHASE_ORDER',
'ADD_PURCHASE_ORDER'=>'ADD_PURCHASE_ORDER',
'PURCHASE_ORDER'=>'PURCHASE_ORDER',
'ALL_ITEMS'=>'ALL_ITEMS',
'ADD_ITEMS'=>'ADD_ITEMS',
'TRANSFER_INVENTORY'=>'TRANSFER_INVENTORY',
'ASSIGNED_STORE'=>'ASSIGNED_STORE',
'SELLER_STORE'=>'SELLER_STORE',
'POS_REPORT'=>'POS_REPORT',
'CREATE_BILL' => 'CREATE_BILL',
'MY_BILLS' =>'MY_BILLS',
'ALL_BILLS' =>'ALL_BILLS',
'BUSINESS_STORE_USER'=>'BUSINESS_STORE_USER',

/*REPORT*/
'ALL_PRODUCT_REPORT'=>'ALL_PRODUCT_REPORT',
'SELLER_PRODUCT_REPORT'=>'SELLER_PRODUCT_REPORT',
'ALL_SKU_REPORT'=>'ALL_SKU_REPORT',
'SELLER_SKU_REPORT'=>'SELLER_SKU_REPORT',
'ALL_SELLER_REPORT'=>'ALL_SELLER_REPORT',
'ALL_CUSTOMER_REPORT'=>'ALL_CUSTOMER_REPORT',
'ALL_CART_REPORT'=>'ALL_CART_REPORT',
'SELLER_CART_REPORT'=>'SELLER_CART_REPORT',
'ALL_WISHLIST_REPORT'=>'ALL_WISHLIST_REPORT',
'SELLER_WISHLIST_REPORT'=>'SELLER_WISHLIST_REPORT',

'ALL_ORDER_REPORT'=>'ALL_ORDER_REPORT',
'SELLER_ORDER_REPORT'=>'SELLER_ORDER_REPORT',

//seller_daashboard
'SELLER_DASHBOARD'=>'SELLER_DASHBOARD',

'BUSINESS_ADD'=>'BUSINESS_ADD',
'BUSINESS_UPDATE'=>'BUSINESS_UPDATE',
'BUSINESS_ALL'=>'BUSINESS_ALL',
];

?>